
all:
	g++ principal.cpp -std=c++17 -I/usr/local/include/opencv4/ -L/usr/local/lib/ -lopencv_core -lopencv_imgproc -lopencv_imgcodecs -lopencv_highgui -lopencv_video -lopencv_videoio -lopencv_objdetect -lopencv_ml  -lopencv_cudaobjdetect -lopencv_cudaimgproc -lopencv_cudawarping -o vision.bin


run:
	./vision.bin
